### ISSUE TITLE
Add .travis.yml file.

### ISSUE THREAD

**Issue by ab-anand** [ab-anand/Bots#1]

**Comment by arpitx165** [comment]
Hi, I want to work on this.I want to know required packages and all.We can refer my repo https://github.com/arpitx165/Parsing-in-Python/blob/master/.travis.yml. Assign it to me

**Comment by ab-anand** [comment]
Great! Let's do it for quora.py The required modules are requests, os, BeautifulSoup, colorama, webbrowser

**Comment by arpitx165** [comment]
Seems like you are setting some proxy server "http://username:pass@192.168.1.107:3128"  I want to know What is this ?

**Comment by ab-anand** [comment]
Yeah! Most of the time I work behind my college proxy server. So it takes care of that.

**Comment by arpitx165** [comment]
Okay, For now, I am commenting that  line, if you want to set up in that way then we can do setting up environment variable in travis.

**Comment by ab-anand** [comment]
Yeah! Sure.

**Comment by arpitx165** [comment]
Hi,You can see my repo https://github.com/arpitx165/Automation-Bots Here i am done with quora.py.I want to suggest few things like you want to build master or want to create new branch so that i can send the pull request.

**Note**: We can't give command line input during build process so I passed command line argument and if you want to test on multiple topics then you can write test cases in a separate file so that we can run during the build.

One problem I faced in your code, sometimes on the same topic, this line works sometimes it doesn't. 
      `ans=soup.findAll('div',{'class':'AnswerHeader ContentHeader'})`

So direct index accessing in ans array may through exception **index out of range**.

**Comment by ab-anand** [comment]
Yeah! I did face the issue. Bdw I have created a branch. You can give PR.

**Comment by arpitx165** [comment]
I have sent PR.Hope you understood changes.Let me know if you face any problem.
